// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.1
// source: analytics.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AnomalyEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceTag     string                 `protobuf:"bytes,1,opt,name=source_tag,json=sourceTag,proto3" json:"source_tag,omitempty"`
	Actual        float64                `protobuf:"fixed64,2,opt,name=actual,proto3" json:"actual,omitempty"`
	Predicted     float64                `protobuf:"fixed64,3,opt,name=predicted,proto3" json:"predicted,omitempty"`
	Residual      float64                `protobuf:"fixed64,4,opt,name=residual,proto3" json:"residual,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,5,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	Severity      string                 `protobuf:"bytes,6,opt,name=severity,proto3" json:"severity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnomalyEvent) Reset() {
	*x = AnomalyEvent{}
	mi := &file_analytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnomalyEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnomalyEvent) ProtoMessage() {}

func (x *AnomalyEvent) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnomalyEvent.ProtoReflect.Descriptor instead.
func (*AnomalyEvent) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{0}
}

func (x *AnomalyEvent) GetSourceTag() string {
	if x != nil {
		return x.SourceTag
	}
	return ""
}

func (x *AnomalyEvent) GetActual() float64 {
	if x != nil {
		return x.Actual
	}
	return 0
}

func (x *AnomalyEvent) GetPredicted() float64 {
	if x != nil {
		return x.Predicted
	}
	return 0
}

func (x *AnomalyEvent) GetResidual() float64 {
	if x != nil {
		return x.Residual
	}
	return 0
}

func (x *AnomalyEvent) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *AnomalyEvent) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

var File_analytics_proto protoreflect.FileDescriptor

const file_analytics_proto_rawDesc = "" +
	"\n" +
	"\x0fanalytics.proto\x12\fhistorian.v1\"\xbe\x01\n" +
	"\fAnomalyEvent\x12\x1d\n" +
	"\n" +
	"source_tag\x18\x01 \x01(\tR\tsourceTag\x12\x16\n" +
	"\x06actual\x18\x02 \x01(\x01R\x06actual\x12\x1c\n" +
	"\tpredicted\x18\x03 \x01(\x01R\tpredicted\x12\x1a\n" +
	"\bresidual\x18\x04 \x01(\x01R\bresidual\x12!\n" +
	"\ftimestamp_ms\x18\x05 \x01(\x03R\vtimestampMs\x12\x1a\n" +
	"\bseverity\x18\x06 \x01(\tR\bseverityB@Z>github.com/ahmetsah/industrial-historian/go-services/pkg/protob\x06proto3"

var (
	file_analytics_proto_rawDescOnce sync.Once
	file_analytics_proto_rawDescData []byte
)

func file_analytics_proto_rawDescGZIP() []byte {
	file_analytics_proto_rawDescOnce.Do(func() {
		file_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_analytics_proto_rawDesc), len(file_analytics_proto_rawDesc)))
	})
	return file_analytics_proto_rawDescData
}

var file_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_analytics_proto_goTypes = []any{
	(*AnomalyEvent)(nil), // 0: historian.v1.AnomalyEvent
}
var file_analytics_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_analytics_proto_init() }
func file_analytics_proto_init() {
	if File_analytics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_analytics_proto_rawDesc), len(file_analytics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_analytics_proto_goTypes,
		DependencyIndexes: file_analytics_proto_depIdxs,
		MessageInfos:      file_analytics_proto_msgTypes,
	}.Build()
	File_analytics_proto = out.File
	file_analytics_proto_goTypes = nil
	file_analytics_proto_depIdxs = nil
}
