// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v4.25.1
// source: query.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HistorianQuery_Query_FullMethodName = "/historian.v1.HistorianQuery/Query"
)

// HistorianQueryClient is the client API for HistorianQuery service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HistorianQueryClient interface {
	Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SensorData], error)
}

type historianQueryClient struct {
	cc grpc.ClientConnInterface
}

func NewHistorianQueryClient(cc grpc.ClientConnInterface) HistorianQueryClient {
	return &historianQueryClient{cc}
}

func (c *historianQueryClient) Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SensorData], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HistorianQuery_ServiceDesc.Streams[0], HistorianQuery_Query_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[QueryRequest, SensorData]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HistorianQuery_QueryClient = grpc.ServerStreamingClient[SensorData]

// HistorianQueryServer is the server API for HistorianQuery service.
// All implementations must embed UnimplementedHistorianQueryServer
// for forward compatibility.
type HistorianQueryServer interface {
	Query(*QueryRequest, grpc.ServerStreamingServer[SensorData]) error
	mustEmbedUnimplementedHistorianQueryServer()
}

// UnimplementedHistorianQueryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHistorianQueryServer struct{}

func (UnimplementedHistorianQueryServer) Query(*QueryRequest, grpc.ServerStreamingServer[SensorData]) error {
	return status.Error(codes.Unimplemented, "method Query not implemented")
}
func (UnimplementedHistorianQueryServer) mustEmbedUnimplementedHistorianQueryServer() {}
func (UnimplementedHistorianQueryServer) testEmbeddedByValue()                        {}

// UnsafeHistorianQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HistorianQueryServer will
// result in compilation errors.
type UnsafeHistorianQueryServer interface {
	mustEmbedUnimplementedHistorianQueryServer()
}

func RegisterHistorianQueryServer(s grpc.ServiceRegistrar, srv HistorianQueryServer) {
	// If the following call panics, it indicates UnimplementedHistorianQueryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HistorianQuery_ServiceDesc, srv)
}

func _HistorianQuery_Query_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(QueryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HistorianQueryServer).Query(m, &grpc.GenericServerStream[QueryRequest, SensorData]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HistorianQuery_QueryServer = grpc.ServerStreamingServer[SensorData]

// HistorianQuery_ServiceDesc is the grpc.ServiceDesc for HistorianQuery service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HistorianQuery_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "historian.v1.HistorianQuery",
	HandlerType: (*HistorianQueryServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Query",
			Handler:       _HistorianQuery_Query_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "query.proto",
}
