# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: analytics.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x61nalytics.proto\x12\x0chistorian.v1\"\x7f\n\x0c\x41nomalyEvent\x12\x12\n\nsource_tag\x18\x01 \x01(\t\x12\x0e\n\x06\x61\x63tual\x18\x02 \x01(\x01\x12\x11\n\tpredicted\x18\x03 \x01(\x01\x12\x10\n\x08residual\x18\x04 \x01(\x01\x12\x14\n\x0ctimestamp_ms\x18\x05 \x01(\x03\x12\x10\n\x08severity\x18\x06 \x01(\tB@Z>github.com/ahmetsah/industrial-historian/go-services/pkg/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analytics_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z>github.com/ahmetsah/industrial-historian/go-services/pkg/proto'
  _globals['_ANOMALYEVENT']._serialized_start=33
  _globals['_ANOMALYEVENT']._serialized_end=160
# @@protoc_insertion_point(module_scope)
