# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\x0chistorian.v1\"U\n\nSensorData\x12\x11\n\tsensor_id\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01\x12\x14\n\x0ctimestamp_ms\x18\x03 \x01(\x03\x12\x0f\n\x07quality\x18\x04 \x01(\x05\"Q\n\x08LogEntry\x12\r\n\x05level\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x14\n\x0ctimestamp_ms\x18\x03 \x01(\x03\x12\x0f\n\x07service\x18\x04 \x01(\t\"U\n\nUserAction\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x02 \x01(\t\x12\x10\n\x08resource\x18\x03 \x01(\t\x12\x14\n\x0ctimestamp_ms\x18\x04 \x01(\x03\"z\n\nAlarmEvent\x12\x10\n\x08\x61larm_id\x18\x01 \x01(\x05\x12\x15\n\rdefinition_id\x18\x02 \x01(\x05\x12\r\n\x05state\x18\x03 \x01(\t\x12\r\n\x05value\x18\x04 \x01(\x01\x12\x14\n\x0ctimestamp_ms\x18\x05 \x01(\x03\x12\x0f\n\x07message\x18\x06 \x01(\tB@Z>github.com/ahmetsah/industrial-historian/go-services/pkg/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z>github.com/ahmetsah/industrial-historian/go-services/pkg/proto'
  _globals['_SENSORDATA']._serialized_start=30
  _globals['_SENSORDATA']._serialized_end=115
  _globals['_LOGENTRY']._serialized_start=117
  _globals['_LOGENTRY']._serialized_end=198
  _globals['_USERACTION']._serialized_start=200
  _globals['_USERACTION']._serialized_end=285
  _globals['_ALARMEVENT']._serialized_start=287
  _globals['_ALARMEVENT']._serialized_end=409
# @@protoc_insertion_point(module_scope)
