# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: query.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bquery.proto\x12\x0chistorian.v1\x1a\x0c\x63ommon.proto\"W\n\x0cQueryRequest\x12\x11\n\tsensor_id\x18\x01 \x01(\t\x12\x10\n\x08start_ts\x18\x02 \x01(\x03\x12\x0e\n\x06\x65nd_ts\x18\x03 \x01(\x03\x12\x12\n\nmax_points\x18\x04 \x01(\x05\x32Q\n\x0eHistorianQuery\x12?\n\x05Query\x12\x1a.historian.v1.QueryRequest\x1a\x18.historian.v1.SensorData0\x01\x42@Z>github.com/ahmetsah/industrial-historian/go-services/pkg/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'query_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z>github.com/ahmetsah/industrial-historian/go-services/pkg/proto'
  _globals['_QUERYREQUEST']._serialized_start=43
  _globals['_QUERYREQUEST']._serialized_end=130
  _globals['_HISTORIANQUERY']._serialized_start=132
  _globals['_HISTORIANQUERY']._serialized_end=213
# @@protoc_insertion_point(module_scope)
